# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-30 06:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('avatar', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('bio', models.TextField(blank=True, null=True)),
                ('tel', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('avatar', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('bio', models.TextField(blank=True, null=True)),
                ('tel', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('avatar', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('bio', models.TextField(blank=True, null=True)),
                ('tel', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='padre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cuentas.Padre'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='cuentas.Profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
