# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_auto_20161201_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tipo',
            field=models.CharField(blank=True, default='Alumno', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='padre',
            name='tipo',
            field=models.CharField(blank=True, default='Padre', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipo',
            field=models.CharField(blank=True, default='Profesor', max_length=8, null=True),
        ),
    ]
