# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0003_auto_20161201_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='cuentas.Padre'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='cuentas.Profesor'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tipo',
            field=models.CharField(default='Alumno', max_length=8),
        ),
        migrations.AlterField(
            model_name='padre',
            name='tipo',
            field=models.CharField(default='Padre', max_length=8),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tipo',
            field=models.CharField(default='Profesor', max_length=8),
        ),
    ]
