# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuentas', '0004_auto_20161202_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(default=0)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='cuentas.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('alumno', models.ManyToManyField(blank=True, null=True, to='cuentas.Alumno')),
                ('profesor', models.ManyToManyField(to='cuentas.Profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='boletas.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Parcial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=1)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parciales', to='boletas.Materia')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion',
            name='parcial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='boletas.Parcial'),
        ),
    ]
