# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='alumno',
            field=models.ManyToManyField(blank=True, to='cuentas.Alumno'),
        ),
    ]
