# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0002_auto_20161202_0537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='alumno',
            new_name='alumnos',
        ),
        migrations.RenameField(
            model_name='grupo',
            old_name='profesor',
            new_name='profesores',
        ),
    ]
