# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletas', '0004_auto_20161208_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='grupos', to='cuentas.Profesor'),
        ),
    ]
